### ISSUE TITLE
BacteriArt Page

### ISSUE THREAD

**Issue by thomasingalls** [bricobio/bricobio-website#1]
- [x] Make the for loop, loop over all elements in the _data.imagesrc file
- [ ] Export photos and save them into /img/ ready for serving

**Comment by zafarali** [comment]
I'll work on these.

**Comment by zafarali** [comment]
For loop was done in acd806760130e2b064a439b2b2342711830521d8
please note that images for this should be saved in `/img/bacteriart/XXXXX.jpg`
