### ISSUE TITLE
Moving towards a website release

### ISSUE THREAD

**Issue by zafarali** [bricobio/bricobio-website#13]
I think the website has been updated quite a bit for a new release, right now bricobio.com doesn't look very professional. We still do need to update the education and the project pages. Please provide the information so I can work on this and we can push a new update by the end of this week?

**Comment by thomasingalls** [comment]
I am in a meeting this morning to update the education info; I'll have the projects update ready shortly after that. Thanks, Zaf!

**Comment by zafarali** [comment]
Hi Thomas, just a reminder that we should be updating the website sometime soon?
