### ISSUE TITLE
Front page to do

### ISSUE THREAD

**Issue by thomasingalls** [bricobio/bricobio-website#2]
- [x] clean up 2-style layout
- [x] fix jumbotron for big, responsive image
- [x] link blog, news to main page content

**Comment by zafarali** [comment]
- [x] "Find your bacteriArt" link doesn't appear on smaller browser sizes
- [x] Would prefer if on #L78 of 0a61d4b23abac0920af88586e8c48414595471fe there were an actual `for` loop instead of the `for in` loop

**Comment by zafarali** [comment]
- [x] I have now made everything into partials. **Please see** this is important for long term code maintainability and for us to easily update sections of the index page without going into the main code of the index page. All partials relating to the homepage are now stored in `_partials/homepage/_XX.jade`

**Comment by zafarali** [comment]
- [x] Found a bug, when you make the screen of the smallest size the 'Who are we?' and the buttons overlap.

**Comment by zafarali** [comment]
Please refer to modularity upgrade on merge #11 to ensure everyone is on the same page.

**Comment by zafarali** [comment]
Can you give me the text and links that need to go into the index page? Once this is done the home page will be a 'go to' resource (albeit needs a bit of a beauty upgrade) and almost everything should be completed!

**Comment by zafarali** [comment]
Text to get:
- [x] What are we doing?
- [x] Why are we doing this?
- [X] Where to find us. (I added a nice map here)
- [x] How to get involved
  Links to get:
- [x] Year of biohacking
- [x] Molecular Biology 101
- [x] Your project here
- [x] contact info
