### ISSUE TITLE
Q: 'upcoming events' on the homepage

### ISSUE THREAD

**Issue by zafarali** [bricobio/bricobio-website#5]
I was just wondering where the data on the 'upcoming events' on the home page should be loaded from, I was thinking we can we can use a `.get()` on the XML provided by google (https://www.google.com/calendar/feeds/l1nv8tbg54emb1p7a1uvj0kr54%40group.calendar.google.com/public/basic) or on the RSS provided by meetup.com (http://www.meetup.com/DIYBio-Montreal/events/rss/)

**Comment by thomasingalls** [comment]
Let’s go for the google calendar events first. Eventually, bricobio will become an entity that doesn’t rely on meetup.com for announcements.

There’s already some code that gets data from the gcal for the News page. Maybe a place to start? Ideally, we’d serve the event name, duration, and location, with a link to another spot on our own website for more details.

**Comment by zafarali** [comment]
Okay, I don't want to use the google calendar widget on the news page because it seems to not fit very nicely on the page, I'll see what I can do using jQuery.
Thanks for the response!

**Comment by zafarali** [comment]
This has been fixed, I reused code from the blog.jade file to display it in a compact way. Loading it using jQuery wasn't working out.
