### ISSUE TITLE
posts/_data.json is not storing authors efficiently

### ISSUE THREAD

**Issue by zafarali** [bricobio/bricobio-website#7]
Hi I just wanted to bring it up that the _data.json file that holds blog posts is not storing the authors correctly. This should be rectified immediately to make it future proof.
Ideally what is now this: 

``` json
{
        "author": {
            "author_1": "Thomas Ingalls",
            "author_2": "Kevin Chen"
        },
        "authorsocialprofile": {
            "authorsocialprofile_1": "http://www.twitter.com/thomasingalls",
            "authorsocialprofile_2": "http://www.twitter.com/bkevinchen"
        },
}
```

Should be:

``` json
{
"author":[ "Thomas Ingalls","Kevin Chen"],
"authorprofile": ["http://www.twitter.com/thomasingalls", "http://www.twitter.com/bkevinchen"],
}
```

Reasons:
- Makes it easier to iterate over the authors
- allows us to account for things like and's and comma's
  ![screen shot 2014-06-17 at 9 33 02 pm](https://cloud.githubusercontent.com/assets/6295292/3308748/aec6468a-f688-11e3-9331-91816e41a2d3.png)
  ![screen shot 2014-06-17 at 9 32 53 pm](https://cloud.githubusercontent.com/assets/6295292/3308749/b305adda-f688-11e3-8caa-b3bf152a6b7d.png)
- Saves space when storing it.

Please give the go ahead and I can change the _data.json file
**WARN: I am not sure how you write the the blog posts. If it is manual then this will go off without a problem, if you have something that automatically encodes it for you then that needs to be changed too to ensure consistency.**

**Comment by thomasingalls** [comment]
everything is manual until we automate parts ourselves in jade

yes please change author storage format - it's something I've wanted to fix

feel free to add/modify/augment the blog section. it's a boilerplate I
inserted with very little modification.

**Comment by zafarali** [comment]
Done. I have updated the template to reflect what it should really be like, but for future ease of access here it is:

``` json
{ 
"template-for-posts": {
        "title": "",
        "summary": "",
        "date_published": "",
        "date_updated": "",
        "authors": [""],
        "authorprofile": [""],
        "thumbnail": ""
    }
}
```
